#include "DyIO/DyIO_def.h"
#include "Namespace/Namespace_bcs_io.h"
#include "Namespace/Namespace_bcs_io_setmode.h"



DATA_STRUCT DATA[NUM_PINS];

void InitPinFunction(void){
	int i;
	for (i=0;i<NUM_PINS;i++){
		DATA[i].FUNCTION.HAS_ANALOG_IN=false; 
		DATA[i].FUNCTION.HAS_PWM=false; 
		DATA[i].FUNCTION.HAS_UART_T=false; 
		DATA[i].FUNCTION.HAS_UART_R=false; 
		DATA[i].FUNCTION.HAS_SPI_C=false; 
		DATA[i].FUNCTION.HAS_SPI_I=false; 
		DATA[i].FUNCTION.HAS_SPI_O=false; 
		DATA[i].FUNCTION. HAS_COUNTER_INPUT_I = false; 
		DATA[i].FUNCTION.HAS_COUNTER_OUTPUT_I = false; 
		DATA[i].FUNCTION. HAS_COUNTER_INPUT_D = false; 
		DATA[i].FUNCTION.HAS_COUNTER_OUTPUT_D = false; 
		DATA[i].FUNCTION. HAS_COUNTER_INPUT_H = false; 
		DATA[i].FUNCTION.HAS_COUNTER_OUTPUT_H = false; 
		DATA[i].FUNCTION.HAS_DC_MOTOR = false; 
		DATA[i].FUNCTION.HAS_PPM=false; 
	}
	DATA[0].FUNCTION.HAS_SPI_C=true; 
	DATA[1].FUNCTION.HAS_SPI_I=true; 
	DATA[2].FUNCTION.HAS_SPI_O=true; 


	DATA[4].FUNCTION.HAS_PWM = true; 
	DATA[5].FUNCTION.HAS_PWM = true; 
	DATA[6].FUNCTION.HAS_PWM = true; 
	DATA[7].FUNCTION.HAS_PWM = true; 

	DATA[4].FUNCTION.HAS_DC_MOTOR = true; 
	DATA[5].FUNCTION.HAS_DC_MOTOR = true; 
	DATA[6].FUNCTION.HAS_DC_MOTOR = true; 
	DATA[7].FUNCTION.HAS_DC_MOTOR = true; 

	DATA[8].FUNCTION.HAS_DC_MOTOR = true; 
	DATA[9].FUNCTION.HAS_DC_MOTOR = true; 
	DATA[10].FUNCTION.HAS_DC_MOTOR = true; 
	DATA[11].FUNCTION.HAS_DC_MOTOR = true; 

	DATA[8].FUNCTION.HAS_ANALOG_IN = true; 
	DATA[9].FUNCTION.HAS_ANALOG_IN = true; 
	DATA[10].FUNCTION.HAS_ANALOG_IN = true; 
	DATA[11].FUNCTION.HAS_ANALOG_IN = true; 

	DATA[12].FUNCTION.HAS_ANALOG_IN = true; 
	DATA[13].FUNCTION.HAS_ANALOG_IN = true; 
	DATA[14].FUNCTION.HAS_ANALOG_IN = true; 
	DATA[15].FUNCTION.HAS_ANALOG_IN = true; 

	DATA[16].FUNCTION.HAS_UART_T =true; 
	DATA[17].FUNCTION.HAS_UART_R =true; 

	//Home buttons
	DATA[0].FUNCTION.HAS_COUNTER_INPUT_H = true; 
	DATA[1].FUNCTION.HAS_COUNTER_INPUT_H = true; 
	DATA[2].FUNCTION.HAS_COUNTER_INPUT_H = true; 
	DATA[3].FUNCTION.HAS_COUNTER_INPUT_H = true; 

	DATA[0].FUNCTION.HAS_COUNTER_OUTPUT_H = true; 
	DATA[1].FUNCTION.HAS_COUNTER_OUTPUT_H = true; 
	DATA[2].FUNCTION.HAS_COUNTER_OUTPUT_H = true; 
	DATA[3].FUNCTION.HAS_COUNTER_OUTPUT_H = true; 
	//Interuptibles

	DATA[17].FUNCTION.HAS_COUNTER_INPUT_I = true; 
	DATA[19].FUNCTION.HAS_COUNTER_INPUT_I = true; 
	DATA[21].FUNCTION.HAS_COUNTER_INPUT_I = true; 
	DATA[23].FUNCTION.HAS_COUNTER_INPUT_I = true; 

	//Direction
	DATA[16].FUNCTION.HAS_COUNTER_INPUT_D = true; 
	DATA[18].FUNCTION.HAS_COUNTER_INPUT_D = true; 
	DATA[20].FUNCTION.HAS_COUNTER_INPUT_D = true; 
	DATA[22].FUNCTION.HAS_COUNTER_INPUT_D = true; 

	//Interuptibles
	DATA[17].FUNCTION.HAS_COUNTER_OUTPUT_I = true; 
	DATA[19].FUNCTION.HAS_COUNTER_OUTPUT_I = true; 
	DATA[21].FUNCTION.HAS_COUNTER_OUTPUT_I = true; 
	DATA[23].FUNCTION.HAS_COUNTER_OUTPUT_I = true; 

	//Direction
	DATA[16].FUNCTION.HAS_COUNTER_OUTPUT_D = true; 
	DATA[18].FUNCTION.HAS_COUNTER_OUTPUT_D = true; 
	DATA[20].FUNCTION.HAS_COUNTER_OUTPUT_D = true; 
	DATA[22].FUNCTION.HAS_COUNTER_OUTPUT_D = true; 

	DATA[23].FUNCTION.HAS_PPM = true; 

	InitilizeBcsIo(	NUM_PINS,
					DATA,
					&SetChanelValueHW,
					&GetChanelValueHW,
					&SetAllChanelValueHW,
					&GetAllChanelValueHW,
					&ConfigureChannelHW
				);
	InitilizeBcsIoSetmode(&setMode);
}
