#include "DyIO/DyIO_def.h"
#include "Namespace/Namespace_bcs_io.h"
#include "Namespace/Namespace_bcs_io_setmode.h"



static DATA_STRUCT DATA[NUM_PINS];

void InitPinFunction(void){
	int i;
	for (i=0;i<NUM_PINS;i++){
		DATA[i].FUNCTION.HAS_ANALOG_IN=FALSE;
		DATA[i].FUNCTION.HAS_PWM=FALSE;
		DATA[i].FUNCTION.HAS_UART_T=FALSE;
		DATA[i].FUNCTION.HAS_UART_R=FALSE;
		DATA[i].FUNCTION.HAS_SPI_C=FALSE;
		DATA[i].FUNCTION.HAS_SPI_I=FALSE;
		DATA[i].FUNCTION.HAS_SPI_O=FALSE;
		DATA[i].FUNCTION. HAS_COUNTER_INPUT_I = FALSE;
		DATA[i].FUNCTION.HAS_COUNTER_OUTPUT_I = FALSE;
		DATA[i].FUNCTION. HAS_COUNTER_INPUT_D = FALSE;
		DATA[i].FUNCTION.HAS_COUNTER_OUTPUT_D = FALSE;
		DATA[i].FUNCTION. HAS_COUNTER_INPUT_H = FALSE;
		DATA[i].FUNCTION.HAS_COUNTER_OUTPUT_H = FALSE;
		DATA[i].FUNCTION.HAS_DC_MOTOR = FALSE;
		DATA[i].FUNCTION.HAS_PPM=FALSE;
	}
	DATA[0].FUNCTION.HAS_SPI_C=TRUE;
	DATA[1].FUNCTION.HAS_SPI_I=TRUE;
	DATA[2].FUNCTION.HAS_SPI_O=TRUE;


	DATA[4].FUNCTION.HAS_PWM = TRUE;
	DATA[5].FUNCTION.HAS_PWM = TRUE;
	DATA[6].FUNCTION.HAS_PWM = TRUE;
	DATA[7].FUNCTION.HAS_PWM = TRUE;

	DATA[4].FUNCTION.HAS_DC_MOTOR = TRUE;
	DATA[5].FUNCTION.HAS_DC_MOTOR = TRUE;
	DATA[6].FUNCTION.HAS_DC_MOTOR = TRUE;
	DATA[7].FUNCTION.HAS_DC_MOTOR = TRUE;

	DATA[8].FUNCTION.HAS_DC_MOTOR = TRUE;
	DATA[9].FUNCTION.HAS_DC_MOTOR = TRUE;
	DATA[10].FUNCTION.HAS_DC_MOTOR = TRUE;
	DATA[11].FUNCTION.HAS_DC_MOTOR = TRUE;

	DATA[8].FUNCTION.HAS_ANALOG_IN = TRUE;
	DATA[9].FUNCTION.HAS_ANALOG_IN = TRUE;
	DATA[10].FUNCTION.HAS_ANALOG_IN = TRUE;
	DATA[11].FUNCTION.HAS_ANALOG_IN = TRUE;

	DATA[12].FUNCTION.HAS_ANALOG_IN = TRUE;
	DATA[13].FUNCTION.HAS_ANALOG_IN = TRUE;
	DATA[14].FUNCTION.HAS_ANALOG_IN = TRUE;
	DATA[15].FUNCTION.HAS_ANALOG_IN = TRUE;

	DATA[16].FUNCTION.HAS_UART_T =TRUE;
	DATA[17].FUNCTION.HAS_UART_R =TRUE;

	//Home buttons
	DATA[0].FUNCTION.HAS_COUNTER_INPUT_H = TRUE;
	DATA[1].FUNCTION.HAS_COUNTER_INPUT_H = TRUE;
	DATA[2].FUNCTION.HAS_COUNTER_INPUT_H = TRUE;
	DATA[3].FUNCTION.HAS_COUNTER_INPUT_H = TRUE;

	DATA[0].FUNCTION.HAS_COUNTER_OUTPUT_H = TRUE;
	DATA[1].FUNCTION.HAS_COUNTER_OUTPUT_H = TRUE;
	DATA[2].FUNCTION.HAS_COUNTER_OUTPUT_H = TRUE;
	DATA[3].FUNCTION.HAS_COUNTER_OUTPUT_H = TRUE;
	//Interuptibles

	DATA[17].FUNCTION.HAS_COUNTER_INPUT_I = TRUE;
	DATA[19].FUNCTION.HAS_COUNTER_INPUT_I = TRUE;
	DATA[21].FUNCTION.HAS_COUNTER_INPUT_I = TRUE;
	DATA[23].FUNCTION.HAS_COUNTER_INPUT_I = TRUE;

	//Direction
	DATA[16].FUNCTION.HAS_COUNTER_INPUT_D = TRUE;
	DATA[18].FUNCTION.HAS_COUNTER_INPUT_D = TRUE;
	DATA[20].FUNCTION.HAS_COUNTER_INPUT_D = TRUE;
	DATA[22].FUNCTION.HAS_COUNTER_INPUT_D = TRUE;

	//Interuptibles
	DATA[17].FUNCTION.HAS_COUNTER_OUTPUT_I = TRUE;
	DATA[19].FUNCTION.HAS_COUNTER_OUTPUT_I = TRUE;
	DATA[21].FUNCTION.HAS_COUNTER_OUTPUT_I = TRUE;
	DATA[23].FUNCTION.HAS_COUNTER_OUTPUT_I = TRUE;

	//Direction
	DATA[16].FUNCTION.HAS_COUNTER_OUTPUT_D = TRUE;
	DATA[18].FUNCTION.HAS_COUNTER_OUTPUT_D = TRUE;
	DATA[20].FUNCTION.HAS_COUNTER_OUTPUT_D = TRUE;
	DATA[22].FUNCTION.HAS_COUNTER_OUTPUT_D = TRUE;

	DATA[23].FUNCTION.HAS_PPM = TRUE;

	InitilizeBcsIo(	NUM_PINS,
					DATA,
					&SetChanelValueHW,
					&GetChanelValueHW,
					&SetAllChanelValueHW,
					&GetAllChanelValueHW,
					&ConfigureChannelHW
				);
	InitilizeBcsIoSetmode(&setMode);
}
